/*This is for INCOME CERTIFICATE
  Generated by Koushikpuppala
  Date:24-Oct_20
  Time:01:00 pm*/
#include <stdio.h>
main()
{
    printf("   ***INCOME CERTIFICATE INFORMATION***\n");
    int x,y,z;
    x=0;
    y=0;
    z=0;
    printf("The balance in the State Bank of India is: ",x);
    scanf("%d",&x);
    printf("The balance in the HDFC Bank is    ......: ",y);
    scanf("%d",&y);
    z=x+y;
    printf("Total balance in the both the Banks......: %d",z);
    getch();
    printf("\n");
}
