/*This is an Transport bill
  Generated by Koushikpuppala
  Date:24-Oct-20
  Time:12:31 pm*/
#include <stdio.h>
main()
{
    int x,y,z;
    x=0;
    y=0;
    z=0;
    printf("   ***Welcome to KOUSHIK TRAVELS***\n");
    printf("The cost for traveling in auto to bus stand is: ",x);
    scanf("%d",&x);
    printf("The cost of bus ticket to travel to kakinada is: ",y);
    scanf("%d",&y);
    z=x+y;
    printf("Total cost for traveling to kakinada is.......: %d",z);
    printf("\n     ***HAPPY JOURNEY***");
    getch();
    printf("\n");
}
